/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AgenceMarketingDigitalMarrakechRouteImport } from './routes/agence-marketing-digital-marrakech'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CastingRouteImport } from './routes/casting'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as SecteursRouteImport } from './routes/secteurs'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as RealisationsIndexRouteImport } from './routes/realisations.index'
import { Route as RealisationsSlugRouteImport } from './routes/realisations.$slug'
import { Route as SecteursIndexRouteImport } from './routes/secteurs.index'
import { Route as SecteursSlugRouteImport } from './routes/secteurs.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceMarketingDigitalMarrakechRoute =
  AgenceMarketingDigitalMarrakechRouteImport.update({
    id: '/agence-marketing-digital-marrakech',
    path: '/agence-marketing-digital-marrakech',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CastingRoute = CastingRouteImport.update({
  id: '/casting',
  path: '/casting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const SecteursRoute = SecteursRouteImport.update({
  id: '/secteurs',
  path: '/secteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const RealisationsIndexRoute = RealisationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RealisationsRoute,
} as any)
const RealisationsSlugRoute = RealisationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RealisationsRoute,
} as any)
const SecteursIndexRoute = SecteursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecteursRoute,
} as any)
const SecteursSlugRoute = SecteursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SecteursRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agence-marketing-digital-marrakech': typeof AgenceMarketingDigitalMarrakechRoute
  '/blog': typeof BlogRouteWithChildren
  '/casting': typeof CastingRoute
  '/contact': typeof ContactRoute
  '/methode': typeof MethodeRoute
  '/realisations': typeof RealisationsRouteWithChildren
  '/secteurs': typeof SecteursRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
  '/secteurs/': typeof SecteursIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agence-marketing-digital-marrakech': typeof AgenceMarketingDigitalMarrakechRoute
  '/casting': typeof CastingRoute
  '/contact': typeof ContactRoute
  '/methode': typeof MethodeRoute
  '/tarifs': typeof TarifsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/realisations': typeof RealisationsIndexRoute
  '/secteurs': typeof SecteursIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agence-marketing-digital-marrakech': typeof AgenceMarketingDigitalMarrakechRoute
  '/blog': typeof BlogRouteWithChildren
  '/casting': typeof CastingRoute
  '/contact': typeof ContactRoute
  '/methode': typeof MethodeRoute
  '/realisations': typeof RealisationsRouteWithChildren
  '/secteurs': typeof SecteursRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
  '/secteurs/': typeof SecteursIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/agence-marketing-digital-marrakech'
    | '/blog'
    | '/casting'
    | '/contact'
    | '/methode'
    | '/realisations'
    | '/secteurs'
    | '/services'
    | '/tarifs'
    | '/blog/$slug'
    | '/realisations/$slug'
    | '/secteurs/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/realisations/'
    | '/secteurs/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/agence-marketing-digital-marrakech'
    | '/casting'
    | '/contact'
    | '/methode'
    | '/tarifs'
    | '/blog/$slug'
    | '/realisations/$slug'
    | '/secteurs/$slug'
    | '/services/$slug'
    | '/blog'
    | '/realisations'
    | '/secteurs'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/agence-marketing-digital-marrakech'
    | '/blog'
    | '/casting'
    | '/contact'
    | '/methode'
    | '/realisations'
    | '/secteurs'
    | '/services'
    | '/tarifs'
    | '/blog/$slug'
    | '/realisations/$slug'
    | '/secteurs/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/realisations/'
    | '/secteurs/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AgenceMarketingDigitalMarrakechRoute: typeof AgenceMarketingDigitalMarrakechRoute
  BlogRoute: typeof BlogRouteWithChildren
  CastingRoute: typeof CastingRoute
  ContactRoute: typeof ContactRoute
  MethodeRoute: typeof MethodeRoute
  RealisationsRoute: typeof RealisationsRouteWithChildren
  SecteursRoute: typeof SecteursRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence-marketing-digital-marrakech': {
      id: '/agence-marketing-digital-marrakech'
      path: '/agence-marketing-digital-marrakech'
      fullPath: '/agence-marketing-digital-marrakech'
      preLoaderRoute: typeof AgenceMarketingDigitalMarrakechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casting': {
      id: '/casting'
      path: '/casting'
      fullPath: '/casting'
      preLoaderRoute: typeof CastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secteurs': {
      id: '/secteurs'
      path: '/secteurs'
      fullPath: '/secteurs'
      preLoaderRoute: typeof SecteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/realisations/': {
      id: '/realisations/'
      path: '/'
      fullPath: '/realisations/'
      preLoaderRoute: typeof RealisationsIndexRouteImport
      parentRoute: typeof RealisationsRoute
    }
    '/realisations/$slug': {
      id: '/realisations/$slug'
      path: '/$slug'
      fullPath: '/realisations/$slug'
      preLoaderRoute: typeof RealisationsSlugRouteImport
      parentRoute: typeof RealisationsRoute
    }
    '/secteurs/': {
      id: '/secteurs/'
      path: '/'
      fullPath: '/secteurs/'
      preLoaderRoute: typeof SecteursIndexRouteImport
      parentRoute: typeof SecteursRoute
    }
    '/secteurs/$slug': {
      id: '/secteurs/$slug'
      path: '/$slug'
      fullPath: '/secteurs/$slug'
      preLoaderRoute: typeof SecteursSlugRouteImport
      parentRoute: typeof SecteursRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface RealisationsRouteChildren {
  RealisationsSlugRoute: typeof RealisationsSlugRoute
  RealisationsIndexRoute: typeof RealisationsIndexRoute
}

const RealisationsRouteChildren: RealisationsRouteChildren = {
  RealisationsSlugRoute: RealisationsSlugRoute,
  RealisationsIndexRoute: RealisationsIndexRoute,
}

const RealisationsRouteWithChildren = RealisationsRoute._addFileChildren(
  RealisationsRouteChildren,
)

interface SecteursRouteChildren {
  SecteursSlugRoute: typeof SecteursSlugRoute
  SecteursIndexRoute: typeof SecteursIndexRoute
}

const SecteursRouteChildren: SecteursRouteChildren = {
  SecteursSlugRoute: SecteursSlugRoute,
  SecteursIndexRoute: SecteursIndexRoute,
}

const SecteursRouteWithChildren = SecteursRoute._addFileChildren(
  SecteursRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AgenceMarketingDigitalMarrakechRoute: AgenceMarketingDigitalMarrakechRoute,
  BlogRoute: BlogRouteWithChildren,
  CastingRoute: CastingRoute,
  ContactRoute: ContactRoute,
  MethodeRoute: MethodeRoute,
  RealisationsRoute: RealisationsRouteWithChildren,
  SecteursRoute: SecteursRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
