/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/methode': typeof MethodeRoute
  '/realisations': typeof RealisationsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/methode': typeof MethodeRoute
  '/realisations': typeof RealisationsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/methode': typeof MethodeRoute
  '/realisations': typeof RealisationsRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/contact'
    | '/methode'
    | '/realisations'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/contact'
    | '/methode'
    | '/realisations'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/blog'
    | '/contact'
    | '/methode'
    | '/realisations'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  MethodeRoute: typeof MethodeRoute
  RealisationsRoute: typeof RealisationsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  MethodeRoute: MethodeRoute,
  RealisationsRoute: RealisationsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
